"""Added login feature

Revision ID: 84afe2f0bb62
Revises: e58d58768eeb
Create Date: 2020-02-13 13:48:04.377291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84afe2f0bb62'
down_revision = 'e58d58768eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('blocked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'blocked_until')
    op.drop_column('users', 'attempts')
    # ### end Alembic commands ###
