"""Added login table

Revision ID: e58d58768eeb
Revises: d20ef3d82612
Create Date: 2020-02-13 09:09:17.600337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58d58768eeb'
down_revision = 'd20ef3d82612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('expires_rt', sa.DateTime(), nullable=False),
    sa.Column('jti_at', sa.String(length=120), nullable=False),
    sa.Column('jti_rt', sa.String(length=120), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti_at'),
    sa.UniqueConstraint('jti_rt')
    )
    op.create_index('idx_expires_rt', 'login_info', ['expires_rt'], unique=False)
    op.create_index('idx_jti_at', 'login_info', ['jti_at'], unique=False)
    op.create_index('idx_jti_rt', 'login_info', ['jti_rt'], unique=False)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_index('idx_jti_rt', table_name='login_info')
    op.drop_index('idx_jti_at', table_name='login_info')
    op.drop_index('idx_expires_rt', table_name='login_info')
    op.drop_table('login_info')
    # ### end Alembic commands ###
